// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerticalSlice.Infrastructure;

#nullable disable

namespace VerticalSlice.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    [Migration("20251107152524_InitMainDb")]
    partial class InitMainDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOnUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOnUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOnUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Headphones, laptops & more",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Keyboards, mice, cables",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kitchen & decor",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Limited time deals",
                            Name = "Sale"
                        });
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@example.com",
                            FirstName = "Demo",
                            LastName = "Customer"
                        });
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOnUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable over-ear, 30h battery.",
                            IsDeleted = false,
                            Name = "Wireless Headphones"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight laptop for work & travel.",
                            IsDeleted = false,
                            Name = "Ultrabook 13\""
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tactile switches, RGB backlight.",
                            IsDeleted = false,
                            Name = "Mechanical Keyboard"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic, multi-device pairing.",
                            IsDeleted = false,
                            Name = "Ergo Mouse"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "8-inch stainless steel blade.",
                            IsDeleted = false,
                            Name = "Chef’s Knife"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Precision spout, stovetop safe.",
                            IsDeleted = false,
                            Name = "Pour-over Kettle"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "60W charge, braided, on sale.",
                            IsDeleted = false,
                            Name = "USB-C Cable (2m)"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedOnUTC = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IPX5 splash-proof, 12h playtime.",
                            IsDeleted = false,
                            Name = "Bluetooth Speaker"
                        });
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Cart", b =>
                {
                    b.HasOne("VerticalSlice.Domain.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("VerticalSlice.Domain.Entities.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("VerticalSlice.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerticalSlice.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Product", b =>
                {
                    b.HasOne("VerticalSlice.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("VerticalSlice.Domain.Entities.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("Price_Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Price");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = 1,
                                    Currency = "USD",
                                    Value = 129.99m
                                },
                                new
                                {
                                    ProductId = 2,
                                    Currency = "USD",
                                    Value = 999.00m
                                },
                                new
                                {
                                    ProductId = 3,
                                    Currency = "USD",
                                    Value = 79.90m
                                },
                                new
                                {
                                    ProductId = 4,
                                    Currency = "USD",
                                    Value = 39.90m
                                },
                                new
                                {
                                    ProductId = 5,
                                    Currency = "USD",
                                    Value = 49.50m
                                },
                                new
                                {
                                    ProductId = 6,
                                    Currency = "USD",
                                    Value = 35.00m
                                },
                                new
                                {
                                    ProductId = 7,
                                    Currency = "USD",
                                    Value = 12.99m
                                },
                                new
                                {
                                    ProductId = 8,
                                    Currency = "USD",
                                    Value = 59.00m
                                });
                        });

                    b.Navigation("Category");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VerticalSlice.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
